prose:
  siteurl: 'https://github.com/Via04/odatav4-guide/tree/master'
  media:
    uploads: "static"
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
metadata:
  _posts:
    - name: "image"
    field:
      element: "string"
      label: "Image URL"
      pattern: "^static"
      placeholder: "static/image.png"
